### ISSUE TITLE
Feature Request: Button to convert keys to insert missing quotes

### ISSUE THREAD

**Issue by Phillbaska** [ryng64/encodeFM#21]
First of all, thanks for such a brilliant and time saving tool. Secondly i'd like to suggest/request a feature. 

Would it be possible to add a button which automatically converts the JSON with no quotes to have quotes?

Currently my workaround is to go to https://jsonformatter.curiousconcept.com/ and paste the JSON into this converter (which automatically adds quotes) then copy into encodeFM.

Thanks again, great tool.

**Comment by ryng64** [comment]
Sorry for the late reply! Thanks for checking this project out and I'm glad it has saved you time on your projects! 

That would be really cool to have it work with or without quotes. I'll look into enabling this as a feature.

**Comment by Phillbaska** [comment]
Awesome, thanks. Please setup a way to support this project like a link to buy you a coffee etc.

**Comment by ryng64** [comment]
Thanks @Phillbaska for the suggestions. I'll definitely look into the project support stuff this weekend. I'll likely continue to work on this feature in the mean time since this is a cool thing to have as a part of this project!
