### ISSUE TITLE
translation issue

### ISSUE THREAD

**Issue by rwu2359** [ryng64/encodeFM#3]
translates
`{"edit":true,"refreshObject":"bar.property"}`

as
JSONSetElement (
    "{}";
    [ "edit" ; "true"; JSONString];
    [ "refreshObject" ; "bar.property"; JSONString]
)

rather than
JSONSetElement (
    "{}";
    [ "edit" ; true; JSONBoolean];
    [ "refreshObject" ; "bar.property"; JSONString]
)

**Comment by ryng64** [comment]
Thanks for the catch! To be honest, I forgot to even test for Booleans. 

Just updated the encodeFM.js & .fmp12 files to check for True/False to be set as JSONBoolean
