### ISSUE TITLE
Problem with escaped characters

### ISSUE THREAD

**Issue by micah-woods** [ryng64/encodeFM#7]
Hello Ryan,

Nice work on this, I found it because I'm working on the same thing, except using native FM. I did some testing and found some issues. One improvement I would suggest is to do a full round trip on the expression, meaning that once the JS calculates the expression, it then calls a FM script that then validates the expression to make sure it's valid.

Here's the issue...

This is valid json:
```json
{
  "backslash": "\\bar\\",
  "quote": "\"foo\""
}
```

But, the resulting expression is not a valid FM calc:
```
JSONSetElement (
    "{}";
    [ "backslash" ; "\bar\"; JSONString];
    [ "quote" ; ""foo""; JSONString]
)
```
The expected result would be:
```
JSONSetElement (
    "{}";
    [ "backslash" ; "\\bar\\"; JSONString];
    [ "quote" ; "\"foo\""; JSONString]
)
```

**Comment by ryng64** [comment]
Hi there Micah, thanks for pointing this out! looks like the / and " are being lost in the javascript before it gets put back together again. I'll take a look at supporting this and validating it!

**Comment by ryng64** [comment]
hopefully this is now fixed in the latest pull request! thanks for reporting the issue with escaped characters! 
#8

**Comment by micah-woods** [comment]
Did a quick test, works as expected!
